#environment with fixed porechop for 96 barcodes
#commands:
# cd ..../rampart_base_folder
#conda env create -f environment_porechop_96.yml
#then in env:
#npm install
#npm run build
#npm install --global 
name: artic-rampart2
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - "python>=3"
  - "nodejs>=12"
  - pip
  - snakemake-minimal=5.8.1
  - biopython=1.74
  - minimap2=2.17
  - pip:
    - binlorry==1.3.0_alpha1
    - git+https://github.com/janka000/Porechop.git@master
