
##### Configuration #####

#print("\nConfig object in Snakefile:")
#[print("\t{} - {}".format(k, v)) for k,v in config.items()]

# trim trailing slashes from paths to avoid snakemake complaining of double '/' in paths
config["path"]=config["annotated_path"].rstrip("/")


##### Target rules #####

rule all:
    input:
        mutations_csv = config["path"]+"/results/mutations.csv"
	
##### Modules #####
include: "rules/merge.smk"
include: "rules/count_and_compare.smk"

